"""init

Revision ID: 346d276315d0
Revises: 
Create Date: 2022-10-22 15:35:24.543922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346d276315d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Account',
    sa.Column('insertDate', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('accountNumber', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('registrationDate', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='InoversityLibraryModel'
    )
    op.create_index(op.f('ix_InoversityLibraryModel_Account_accountNumber'), 'Account', ['accountNumber'], unique=True, schema='InoversityLibraryModel')
    op.create_index(op.f('ix_InoversityLibraryModel_Account_id'), 'Account', ['id'], unique=False, schema='InoversityLibraryModel')
    op.create_table('Staff',
    sa.Column('insertDate', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('roleLevel', sa.String(length=256), nullable=False),
    sa.Column('staffNumber', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('jobTitle', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staffNumber'),
    schema='InoversityLibraryModel'
    )
    op.create_index(op.f('ix_InoversityLibraryModel_Staff_id'), 'Staff', ['id'], unique=False, schema='InoversityLibraryModel')
    op.create_index(op.f('ix_InoversityLibraryModel_Staff_roleLevel'), 'Staff', ['roleLevel'], unique=False, schema='InoversityLibraryModel')
    op.create_table('Student',
    sa.Column('insertDate', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('roleLevel', sa.String(length=256), nullable=False),
    sa.Column('studentNumber', sa.String(length=20), nullable=False),
    sa.Column('faculty', sa.String(length=100), nullable=False),
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('programme', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentNumber'),
    schema='InoversityLibraryModel'
    )
    op.create_index(op.f('ix_InoversityLibraryModel_Student_id'), 'Student', ['id'], unique=False, schema='InoversityLibraryModel')
    op.create_index(op.f('ix_InoversityLibraryModel_Student_roleLevel'), 'Student', ['roleLevel'], unique=False, schema='InoversityLibraryModel')
    op.create_table('UserType',
    sa.Column('insertDate', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('userType', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userType'),
    schema='InoversityLibraryModel'
    )
    op.create_index(op.f('ix_InoversityLibraryModel_UserType_id'), 'UserType', ['id'], unique=False, schema='InoversityLibraryModel')
    op.create_table('User',
    sa.Column('insertDate', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('emailAddress', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('userTypeId', sa.INTEGER(), nullable=False),
    sa.Column('accountId', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['accountId'], ['InoversityLibraryModel.Account.id'], ),
    sa.ForeignKeyConstraint(['userTypeId'], ['InoversityLibraryModel.UserType.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='InoversityLibraryModel'
    )
    op.create_index(op.f('ix_InoversityLibraryModel_User_id'), 'User', ['id'], unique=False, schema='InoversityLibraryModel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_InoversityLibraryModel_User_id'), table_name='User', schema='InoversityLibraryModel')
    op.drop_table('User', schema='InoversityLibraryModel')
    op.drop_index(op.f('ix_InoversityLibraryModel_UserType_id'), table_name='UserType', schema='InoversityLibraryModel')
    op.drop_table('UserType', schema='InoversityLibraryModel')
    op.drop_index(op.f('ix_InoversityLibraryModel_Student_roleLevel'), table_name='Student', schema='InoversityLibraryModel')
    op.drop_index(op.f('ix_InoversityLibraryModel_Student_id'), table_name='Student', schema='InoversityLibraryModel')
    op.drop_table('Student', schema='InoversityLibraryModel')
    op.drop_index(op.f('ix_InoversityLibraryModel_Staff_roleLevel'), table_name='Staff', schema='InoversityLibraryModel')
    op.drop_index(op.f('ix_InoversityLibraryModel_Staff_id'), table_name='Staff', schema='InoversityLibraryModel')
    op.drop_table('Staff', schema='InoversityLibraryModel')
    op.drop_index(op.f('ix_InoversityLibraryModel_Account_id'), table_name='Account', schema='InoversityLibraryModel')
    op.drop_index(op.f('ix_InoversityLibraryModel_Account_accountNumber'), table_name='Account', schema='InoversityLibraryModel')
    op.drop_table('Account', schema='InoversityLibraryModel')
    # ### end Alembic commands ###
